(()=>{const db=firebase.database(),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const D={en:{heroK:'SIGNATURE SELECTION',heroT:'Choose your <em>moment.</em>',heroL:'Move the circle with your finger or let it glide slowly. Tap an item, then tap the large image for details.',hint:'DRAG · TAP AN ITEM',menu:'Open menu',galleryK:'FIND US',galleryT:'Recognize your Cup And Go.',signK:'OUR IDENTITY',signT:'The sign you remember.',signEmpty:'Upload your signboard artwork from Admin',aboutK:'ABOUT CUP AND GO',aboutT:'Made for your <em>everyday.</em>',about:'Welcome to Cup And Go. We serve fresh coffee and drinks made for everyday moments. Our menu includes Coffee Day, V60, Matcha, Hibiscus, cold drinks, sweets and sharing boxes. We focus on fast service, premium quality and a simple experience. Open the menu anytime to see our latest drinks and offers.',cats:'WHAT YOU CAN FIND HERE',contacts:'Visit & Contact Cup And Go',loc:'Location',wa:'WhatsApp',ig:'Instagram',tk:'TikTok',dev:'Developer: Mohammed Ashik',photo:'Cup And Go · Store view',details:'ITEM DETAILS'},
ar:{heroK:'اختيارات كوب أند جو',heroT:'اختر <em>مزاجك.</em>',heroL:'حرّك الدائرة بإصبعك أو اتركها تتحرك بهدوء. اختر الصنف ثم اضغط على الصورة الكبيرة لعرض التفاصيل.',hint:'حرّك · اختر الصنف',menu:'افتح المنيو',galleryK:'زورونا',galleryT:'تعرّف على كوب أند جو.',signK:'هويتنا',signT:'علامة تتذكرها.',signEmpty:'ارفع تصميم لوحة المتجر من لوحة الإدارة',aboutK:'عن كوب أند جو',aboutT:'مصمم <em>ليومك.</em>',about:'مرحباً بكم في كوب أند جو. نقدم القهوة والمشروبات الطازجة لكل يوم. في المنيو تجد قهوة اليوم، V60، الماتشا، الكركديه، المشروبات الباردة، الحلويات وبوكسات المشاركة. نهتم بالخدمة السريعة والجودة الممتازة والتجربة السهلة. افتح المنيو في أي وقت لمشاهدة أحدث المشروبات والعروض.',cats:'ماذا تجد في منيو كوب أند جو',contacts:'زورونا وتواصلوا معنا',loc:'الموقع',wa:'واتساب',ig:'إنستغرام',tk:'تيك توك',dev:'المطور: Mohammed Ashik',photo:'كوب أند جو · صورة المتجر',details:'تفاصيل الصنف'}};
const CAT_AR={'Coffee':'قهوة','Sweet':'حلويات','Coffee Box':'بوكس القهوة','Sweet Box':'بوكس الحلويات','Cold Drink':'مشروبات باردة','Cold Drinks':'مشروبات باردة','Special Offer':'العروض الخاصة','Tea':'شاي','Matcha':'ماتشا','Breakfast':'فطور','Dessert':'حلويات','Offers':'العروض','Other':'أخرى'};
let lang=localStorage.getItem('cng_website_lang')||'en',settings={},cfg={},products=[],featured=[],active=0,turn=0,drag=false,lastA=0,galleryIndex=0,galleryTimer=null,sigS='',sigP='',sigC='',lastTs=0,pauseUntil=0,raf=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pid=p=>String(p&&(p.id!=null?p.id:(p.name||''))||''),pimg=p=>String(p&&(p.imageHD||p.imageHd||p.hdImage||p.icon||p.image)||''),pname=p=>String(p&&(lang==='ar'?(p.nameAr||p.arName||p.name):(p.name||p.nameEn||p.nameAr))||''),pdesc=p=>String(p&&(lang==='ar'?(p.descriptionAr||p.descAr||p.description):(p.description||p.desc||p.descriptionAr))||''),pcat=p=>String(p&&p.category||'Other').replace(/^\s*[^\p{L}\p{N}]+/u,'').trim()||'Other';
const sig=v=>{try{return JSON.stringify(v)}catch(e){return String(v)}},norm=v=>{v%=360;if(v>180)v-=360;if(v<-180)v+=360;return v},menuUrl=()=>cfg.menuUrl||'https://cupandgo-ksa.github.io/cup-and-go-menu/';
const social=(v,b)=>{v=String(v||'').trim();return !v?'':/^https?:\/\//i.test(v)?v:b+v.replace(/^@/,'')},wa=v=>{const n=String(v||'').replace(/\D/g,'');return n?'https://wa.me/'+n:''};
function buildFeatured(){let slides=Array.isArray(cfg.slides)?cfg.slides.filter(Boolean).slice(0,6):[];if(!slides.length)slides=products.filter(x=>pimg(x)).slice(0,6).map(p=>({productId:pid(p)}));featured=slides.map((s,i)=>{let p=s.productId?products.find(x=>pid(x)===String(s.productId)):null;if(!p)p=products.filter(x=>pimg(x))[i]||products[i]||null;return{p,name:p?pname(p):((s.top||'')+' '+(s.bottom||'')).trim()||'Cup And Go',desc:p?pdesc(p):(lang==='ar'?(s.arDesc||s.desc||''):(s.desc||s.arDesc||'')),image:String(s.imageUrl||pimg(p)||''),cat:p?pcat(p):(s.type||'Signature'),accent:s.accent||'#e5c158'}});if(!featured.length)featured=[{name:'Cup And Go',desc:'',image:'',cat:'Coffee',accent:'#e5c158'}];active=Math.min(active,featured.length-1)}
function renderBrand(){const logo=q('#brandLogo'),name=q('#brandName');if(settings.shopLogo)logo.innerHTML='<img src="'+esc(settings.shopLogo)+'" alt="">';else logo.textContent='C&G';if(cfg.brandImageUrl)name.innerHTML='<img class="brand-name-img" src="'+esc(cfg.brandImageUrl)+'" alt="'+esc(settings.shopName||'Cup And Go')+'">';else name.innerHTML='<span class="brand-name-text">'+esc(settings.shopName||cfg.brandName||'Cup And Go')+'</span>';const wc=q('#wheelCenter');wc.innerHTML=settings.shopLogo?'<img src="'+esc(settings.shopLogo)+'" alt="">':'<span>'+esc(settings.shopName||'Cup And Go')+'</span>'}
function angleOf(i){return 360/featured.length*i}
function drawWheel(){const wheel=q('#wheel');qa('.node').forEach(n=>n.remove());featured.forEach((f,i)=>{const b=document.createElement('button');b.className='node'+(i===active?' active':'');b.style.setProperty('--a',angleOf(i)+'deg');b.dataset.i=i;b.innerHTML='<span class="node-inner">'+(f.image?'<img src="'+esc(f.image)+'" alt="" loading="'+(i<2?'eager':'lazy')+'" decoding="async">':'<span>'+esc(f.name.split(/\s+/)[0])+'</span>')+'</span>';b.addEventListener('click',e=>{e.stopPropagation();pauseUntil=performance.now()+3500;select(i,true)});wheel.appendChild(b)});wheel.style.setProperty('--turn',turn+'deg')}
function markActive(){qa('.node').forEach((n,i)=>n.classList.toggle('active',i===active))}
function select(i,animate){if(!featured.length)return;active=(i+featured.length)%featured.length;turn+=norm(-angleOf(active)-turn);q('#wheel').style.setProperty('--turn',turn+'deg');markActive();showPreview(animate);hideInfo()}
function showPreview(anim){const f=featured[active];if(!f)return;const p=q('#preview');if(anim){p.classList.add('switch');setTimeout(()=>p.classList.remove('switch'),230)}const im=q('#previewImg');if(f.image){im.src=f.image;im.hidden=false}else{im.removeAttribute('src');im.hidden=true}}
function showInfo(){const f=featured[active],t=D[lang];if(!f)return;q('#infoMini').textContent=t.details;q('#infoName').textContent=f.name;q('#infoDesc').textContent=f.desc||'';q('#infoPop').classList.add('show');pauseUntil=performance.now()+5500}
function hideInfo(){q('#infoPop').classList.remove('show')}
function ptrA(e){const r=q('#wheel').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;return Math.atan2(e.clientY-cy,e.clientX-cx)*180/Math.PI}
function closest(animate=true){let best=0,dist=1e9;featured.forEach((_,i)=>{const d=Math.abs(norm(turn+angleOf(i)));if(d<dist){dist=d;best=i}});if(best!==active){active=best;markActive();showPreview(animate);hideInfo()}}
function bindWheel(){const wheel=q('#wheel');wheel.onpointerdown=e=>{drag=true;pauseUntil=performance.now()+2500;lastA=ptrA(e);wheel.setPointerCapture?.(e.pointerId);e.preventDefault()};wheel.onpointermove=e=>{if(!drag)return;const a=ptrA(e);turn+=norm(a-lastA);lastA=a;wheel.style.setProperty('--turn',turn+'deg');closest(true);e.preventDefault()};const end=e=>{if(!drag)return;drag=false;pauseUntil=performance.now()+2200;wheel.releasePointerCapture?.(e.pointerId)};wheel.onpointerup=end;wheel.onpointercancel=end}
function autoRotate(ts){if(!lastTs)lastTs=ts;const dt=Math.min(40,ts-lastTs);lastTs=ts;if(!drag&&ts>pauseUntil&&featured.length>1){turn+=dt*.0042;q('#wheel').style.setProperty('--turn',turn+'deg');closest(false)}raf=requestAnimationFrame(autoRotate)}
function gallery(){const t=D[lang],pics=(Array.isArray(cfg.storeGallery)?cfg.storeGallery:[]).filter(Boolean).slice(0,3),arr=pics.length?pics:[null,null,null],track=q('#galleryTrack'),dots=q('#galleryDots');galleryIndex=Math.min(galleryIndex,arr.length-1);track.innerHTML=arr.map((u,i)=>'<article class="gallery-card'+(i===galleryIndex?' active':'')+'">'+(u?'<img src="'+esc(u)+'" alt="'+esc(t.photo)+' '+(i+1)+'" loading="'+(i===0?'eager':'lazy')+'" decoding="async">':'<div style="width:100%;height:100%;display:grid;place-items:center;padding:25px;text-align:center;color:#65756b;font:italic 20px Cormorant Garamond,serif;">'+(lang==='ar'?'ارفع صورة المتجر من لوحة الإدارة':'Upload store photo from Admin')+'</div>')+'<div class="gallery-label"><b>'+esc(settings.shopName||'Cup And Go')+'</b><small>'+esc(t.photo)+'</small></div></article>').join('');dots.innerHTML=arr.map((_,i)=>'<button class="gallery-dot'+(i===galleryIndex?' active':'')+'" data-i="'+i+'"></button>').join('');qa('.gallery-dot').forEach(b=>b.onclick=()=>{galleryIndex=+b.dataset.i;moveGallery()});clearInterval(galleryTimer);galleryTimer=setInterval(()=>{galleryIndex=(galleryIndex+1)%arr.length;moveGallery()},4300);moveGallery()}
function moveGallery(){const track=q('#galleryTrack'),cards=qa('.gallery-card');if(!cards.length)return;const step=cards[0].getBoundingClientRect().width+12;track.style.transform='translateX('+(-galleryIndex*step)+'px)';cards.forEach((c,i)=>c.classList.toggle('active',i===galleryIndex));qa('.gallery-dot').forEach((d,i)=>d.classList.toggle('active',i===galleryIndex))}
function renderSign(){const t=D[lang],im=q('#signImg'),ph=q('#signEmpty');q('#signK').textContent=t.signK;q('#signT').textContent=t.signT;if(cfg.signboardImageUrl){im.src=cfg.signboardImageUrl;im.hidden=false;ph.hidden=true}else{im.removeAttribute('src');im.hidden=true;ph.hidden=false;ph.textContent=t.signEmpty}}
function renderText(){const t=D[lang],ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';q('#heroK').textContent=t.heroK;q('#heroT').innerHTML=t.heroT;q('#heroL').textContent=t.heroL;q('#wheelHint').textContent=t.hint;q('#menuCtaText').textContent=t.menu;q('#menuCta').href=menuUrl();q('#headerMenu').href=menuUrl();q('#galleryK').textContent=t.galleryK;q('#galleryT').textContent=t.galleryT;q('#aboutK').textContent=t.aboutK;q('#aboutT').innerHTML=ar?(cfg.aboutTitleAr||t.aboutT):(cfg.aboutTitleEn||t.aboutT);q('#aboutText').textContent=ar?(cfg.aboutTextAr||t.about):(cfg.aboutTextEn||t.about);q('#contactTitle').textContent=t.contacts;q('#dev').innerHTML='<b>'+esc(t.dev)+'</b>';q('#langBtn').textContent=ar?'EN':'AR';renderSign()}
function renderCats(){return}
function link(id,url,label){const a=q(id);a.hidden=!url;if(url)a.href=url;a.querySelector('span').textContent=label}
function renderContacts(){const t=D[lang];link('#loc',String(cfg.locationUrl||''),t.loc);link('#wa',wa(cfg.whatsapp||''),t.wa);link('#ig',social(cfg.instagram||'','https://instagram.com/'),t.ig);link('#tk',social(cfg.tiktok||'','https://www.tiktok.com/@'),t.tk)}
function render(){buildFeatured();renderBrand();renderText();renderContacts();drawWheel();showPreview(false);gallery()}
const THEME_PALETTES=[
 {base:'#07130e',glow:'#35572d',gold:'#e5c158'},
 {base:'#190b0d',glow:'#6f2930',gold:'#efc88b'},
 {base:'#160f09',glow:'#704724',gold:'#e2b565'},
 {base:'#0b1518',glow:'#28515a',gold:'#d7c78f'},
 {base:'#160d15',glow:'#5c3156',gold:'#e7bd92'}
];let themeIndex=0,themeTimer=null;
function applyTheme(i){const p=THEME_PALETTES[i%THEME_PALETTES.length];document.documentElement.style.setProperty('--theme-base',p.base);document.documentElement.style.setProperty('--theme-glow',p.glow);document.documentElement.style.setProperty('--gold',p.gold)}
function startThemes(){clearInterval(themeTimer);applyTheme(themeIndex);themeTimer=setInterval(()=>{themeIndex=(themeIndex+1)%THEME_PALETTES.length;applyTheme(themeIndex)},7800)}
function setupPremiumReveal(){const els=[q('.about'),q('.contacts')].filter(Boolean);els.forEach(el=>el.classList.add('fx-reveal'));const io2=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.14});els.forEach(el=>io2.observe(el))}
function init(){bindWheel();q('#preview').onclick=showInfo;q('#infoClose').onclick=hideInfo;q('#langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('cng_website_lang',lang);render()};let sx=0;const gv=q('#galleryViewport');gv.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});gv.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,n=qa('.gallery-card').length;if(Math.abs(dx)>40&&n){galleryIndex=(galleryIndex+(dx<0?1:-1)+n)%n;moveGallery()}},{passive:true});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('reveal')}),{threshold:.18});io.observe(q('#gallery'));io.observe(q('#signboard'));addEventListener('resize',()=>{drawWheel();moveGallery()},{passive:true});cancelAnimationFrame(raf);raf=requestAnimationFrame(autoRotate);startThemes();setupPremiumReveal()}
Promise.all([db.ref('/settings').once('value'),db.ref('/products').once('value'),db.ref('/website/config').once('value')]).then(([s,p,c])=>{settings=s.val()||{};const d=p.val();products=d?Object.values(d).filter(Boolean):[];cfg=c.val()||{};sigS=sig(settings);sigP=sig(products);sigC=sig(cfg);render();init();db.ref('/settings').on('value',x=>{const v=x.val()||{},z=sig(v);if(z===sigS)return;sigS=z;settings=v;render()});db.ref('/products').on('value',x=>{const d=x.val(),v=d?Object.values(d).filter(Boolean):[],z=sig(v);if(z===sigP)return;sigP=z;products=v;render()});db.ref('/website/config').on('value',x=>{const v=x.val()||{},z=sig(v);if(z===sigC)return;sigC=z;cfg=v;render()})}).catch(()=>{render();init()});
})();