(()=>{const db=firebase.database(),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const D={en:{heroK:'SIGNATURE SELECTION',heroT:'Choose your <em>moment.</em>',heroL:'Move the circle with your finger. Tap an item to bring it forward and see every detail.',hint:'DRAG THE CIRCLE · TAP AN ITEM',galleryK:'FIND US',galleryT:'Recognize your Cup And Go.',aboutK:'ABOUT CUP AND GO',aboutT:'Made for your <em>everyday.</em>',about:'Cup And Go is a Saudi coffee shop built around quick service, fresh drinks and a premium experience that still feels easy. We serve everyday coffee, V60, matcha, hibiscus, cold drinks, sweets, coffee boxes, sweet boxes and selected offers. Whether you are stopping by for a fast cup or choosing something to share, our menu is designed to keep the experience simple, clear and enjoyable.',cats:'WHAT YOU CAN FIND HERE',contacts:'Find & follow us',loc:'Location',wa:'WhatsApp',ig:'Instagram',tk:'TikTok',dev:'Developer: Mohammed Ashik',photo:'Cup And Go · Store view'},ar:{heroK:'اختيارات كوب أند جو',heroT:'اختر <em>مزاجك.</em>',heroL:'حرّك الدائرة بإصبعك واضغط على أي صنف ليظهر بشكل أكبر مع جميع التفاصيل.',hint:'حرّك الدائرة · اضغط على الصنف',galleryK:'زورونا',galleryT:'تعرّف على كوب أند جو.',aboutK:'عن كوب أند جو',aboutT:'مصمم <em>ليومك.</em>',about:'كوب أند جو مقهى في السعودية يجمع بين الخدمة السريعة والمشروبات الطازجة والتجربة الراقية والبسيطة. نقدم قهوة اليوم، V60، الماتشا، الكركديه، المشروبات الباردة، الحلويات، بوكسات القهوة، بوكسات الحلويات والعروض المختارة. سواء كنت تريد كوباً سريعاً أو شيئاً للمشاركة، صممنا المنيو لتكون التجربة واضحة وسهلة وممتعة.',cats:'ماذا تجد في منيو كوب أند جو',contacts:'موقعنا وحساباتنا',loc:'الموقع',wa:'واتساب',ig:'إنستغرام',tk:'تيك توك',dev:'المطور: Mohammed Ashik',photo:'كوب أند جو · صورة المتجر'}};
const CAT_AR={'Coffee':'قهوة','Sweet':'حلويات','Coffee Box':'بوكس القهوة','Sweet Box':'بوكس الحلويات','Cold Drink':'مشروبات باردة','Cold Drinks':'مشروبات باردة','Special Offer':'العروض الخاصة','Tea':'شاي','Matcha':'ماتشا','Breakfast':'فطور','Dessert':'حلويات','Offers':'العروض','Other':'أخرى'};
let lang=localStorage.getItem('cng_website_lang')||'en',settings={},cfg={},products=[],featured=[],active=0,turn=0,drag=false,lastA=0,galleryIndex=0,galleryTimer=null,sigS='',sigP='',sigC='';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pid=p=>String(p&&(p.id!=null?p.id:(p.name||''))||''),pimg=p=>String(p&&(p.imageHD||p.imageHd||p.hdImage||p.icon||p.image)||''),pname=p=>String(p&&(lang==='ar'?(p.nameAr||p.arName||p.name):(p.name||p.nameEn||p.nameAr))||''),pdesc=p=>String(p&&(lang==='ar'?(p.descriptionAr||p.descAr||p.description):(p.description||p.desc||p.descriptionAr))||''),pcat=p=>String(p&&p.category||'Other').replace(/^\s*[^\p{L}\p{N}]+/u,'').trim()||'Other';
const sig=v=>{try{return JSON.stringify(v)}catch(e){return String(v)}},norm=v=>{v%=360;if(v>180)v-=360;if(v<-180)v+=360;return v},menuUrl=()=>cfg.menuUrl||'https://cupandgo-ksa.github.io/cup-and-go-menu/';
const social=(v,b)=>{v=String(v||'').trim();return !v?'':/^https?:\/\//i.test(v)?v:b+v.replace(/^@/,'')},wa=v=>{const n=String(v||'').replace(/\D/g,'');return n?'https://wa.me/'+n:''};
function buildFeatured(){let slides=Array.isArray(cfg.slides)?cfg.slides.filter(Boolean).slice(0,6):[];if(!slides.length)slides=products.filter(x=>pimg(x)).slice(0,6).map(p=>({productId:pid(p)}));featured=slides.map((s,i)=>{let p=s.productId?products.find(x=>pid(x)===String(s.productId)):null;if(!p)p=products.filter(x=>pimg(x))[i]||products[i]||null;return{p,name:p?pname(p):((s.top||'')+' '+(s.bottom||'')).trim()||'Cup And Go',desc:p?pdesc(p):(lang==='ar'?(s.arDesc||s.desc||''):(s.desc||s.arDesc||'')),image:String(s.imageUrl||pimg(p)||''),cat:p?pcat(p):(s.type||'Signature'),price:p?Number(p.price||0):0,accent:s.accent||'#e5c158'}});if(!featured.length)featured=[{name:'Cup And Go',desc:'',image:'',cat:'Coffee',price:0,accent:'#e5c158'}];active=Math.min(active,featured.length-1)}
function renderBrand(){const logo=q('#brandLogo'),name=q('#brandName');if(settings.shopLogo)logo.innerHTML='<img src="'+esc(settings.shopLogo)+'" alt="">';else logo.textContent='C&G';if(cfg.brandImageUrl)name.innerHTML='<img class="brand-name-img" src="'+esc(cfg.brandImageUrl)+'" alt="'+esc(settings.shopName||'Cup And Go')+'">';else name.innerHTML='<span class="brand-name-text">'+esc(settings.shopName||cfg.brandName||'Cup And Go')+'</span>';const wc=q('#wheelCenter');wc.innerHTML=settings.shopLogo?'<img src="'+esc(settings.shopLogo)+'" alt="">':'<span>'+esc(settings.shopName||'Cup And Go')+'</span>'}
function angleOf(i){return 360/featured.length*i}
function drawWheel(){const wheel=q('#wheel');qa('.node').forEach(n=>n.remove());featured.forEach((f,i)=>{const b=document.createElement('button');b.className='node'+(i===active?' active':'');b.style.setProperty('--a',angleOf(i)+'deg');b.dataset.i=i;b.innerHTML='<span class="node-inner">'+(f.image?'<img src="'+esc(f.image)+'" alt="" loading="'+(i<2?'eager':'lazy')+'" decoding="async">':'<span>'+esc(f.name.split(/\s+/)[0])+'</span>')+'</span>';b.addEventListener('click',e=>{e.stopPropagation();select(i,true)});wheel.appendChild(b)});wheel.style.setProperty('--turn',turn+'deg')}
function markActive(){qa('.node').forEach((n,i)=>n.classList.toggle('active',i===active))}
function select(i,animate){if(!featured.length)return;active=(i+featured.length)%featured.length;turn+=norm(-angleOf(active)-turn);q('#wheel').style.setProperty('--turn',turn+'deg');markActive();showDetail(animate)}
function showDetail(anim){const f=featured[active];if(!f)return;document.documentElement.style.setProperty('--gold',f.accent||'#e5c158');const d=q('#detail');if(anim){d.classList.add('switch');setTimeout(()=>d.classList.remove('switch'),230)}const im=q('#detailImg');if(f.image){im.src=f.image;im.hidden=false}else{im.removeAttribute('src');im.hidden=true}q('#detailIndex').textContent=String(active+1).padStart(2,'0')+' / '+String(featured.length).padStart(2,'0');q('#detailName').textContent=f.name;q('#detailDesc').textContent=f.desc||'';q('#detailCat').textContent=lang==='ar'?(CAT_AR[f.cat]||f.cat):f.cat;q('#detailPrice').textContent=f.price?f.price.toFixed(2)+' ﷼':''}
function ptrA(e){const r=q('#wheel').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;return Math.atan2(e.clientY-cy,e.clientX-cx)*180/Math.PI}
function closest(){let best=0,dist=1e9;featured.forEach((_,i)=>{const d=Math.abs(norm(turn+angleOf(i)));if(d<dist){dist=d;best=i}});if(best!==active){active=best;markActive();showDetail(true)}}
function bindWheel(){const wheel=q('#wheel');wheel.onpointerdown=e=>{drag=true;lastA=ptrA(e);wheel.setPointerCapture?.(e.pointerId);e.preventDefault()};wheel.onpointermove=e=>{if(!drag)return;const a=ptrA(e);turn+=norm(a-lastA);lastA=a;wheel.style.setProperty('--turn',turn+'deg');closest();e.preventDefault()};const end=e=>{if(!drag)return;drag=false;wheel.releasePointerCapture?.(e.pointerId);select(active,false)};wheel.onpointerup=end;wheel.onpointercancel=end}
function gallery(){const t=D[lang],pics=(Array.isArray(cfg.storeGallery)?cfg.storeGallery:[]).filter(Boolean).slice(0,3),arr=pics.length?pics:[null,null,null],track=q('#galleryTrack'),dots=q('#galleryDots');galleryIndex=Math.min(galleryIndex,arr.length-1);track.innerHTML=arr.map((u,i)=>'<article class="gallery-card'+(i===galleryIndex?' active':'')+'">'+(u?'<img src="'+esc(u)+'" alt="'+esc(t.photo)+' '+(i+1)+'" loading="'+(i===0?'eager':'lazy')+'" decoding="async">':'<div style="width:100%;height:100%;display:grid;place-items:center;padding:25px;text-align:center;color:#65756b;font:italic 20px Cormorant Garamond,serif;">'+(lang==='ar'?'ارفع صورة المتجر من لوحة الإدارة':'Upload store photo from Admin')+'</div>')+'<div class="gallery-label"><b>'+esc(settings.shopName||'Cup And Go')+'</b><small>'+esc(t.photo)+'</small></div></article>').join('');dots.innerHTML=arr.map((_,i)=>'<button class="gallery-dot'+(i===galleryIndex?' active':'')+'" data-i="'+i+'"></button>').join('');qa('.gallery-dot').forEach(b=>b.onclick=()=>{galleryIndex=+b.dataset.i;moveGallery()});clearInterval(galleryTimer);galleryTimer=setInterval(()=>{galleryIndex=(galleryIndex+1)%arr.length;moveGallery()},4300);moveGallery()}
function moveGallery(){const track=q('#galleryTrack'),cards=qa('.gallery-card');if(!cards.length)return;const step=cards[0].getBoundingClientRect().width+12;track.style.transform='translateX('+(-galleryIndex*step)+'px)';cards.forEach((c,i)=>c.classList.toggle('active',i===galleryIndex));qa('.gallery-dot').forEach((d,i)=>d.classList.toggle('active',i===galleryIndex))}
function renderText(){const t=D[lang],ar=lang==='ar';document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';q('#heroK').textContent=t.heroK;q('#heroT').innerHTML=t.heroT;q('#heroL').textContent=t.heroL;q('#wheelHint').textContent=t.hint;q('#galleryK').textContent=t.galleryK;q('#galleryT').textContent=t.galleryT;q('#aboutK').textContent=t.aboutK;q('#aboutT').innerHTML=ar?(cfg.aboutTitleAr||t.aboutT):(cfg.aboutTitleEn||t.aboutT);q('#aboutText').textContent=ar?(cfg.aboutTextAr||t.about):(cfg.aboutTextEn||t.about);q('#catTitle').textContent=t.cats;q('#contactTitle').textContent=t.contacts;q('#dev').innerHTML='<b>'+esc(t.dev)+'</b>';q('#langBtn').textContent=ar?'EN':'AR'}
function renderCats(){const list=[];products.forEach(p=>{const c=pcat(p);if(c&&!list.includes(c))list.push(c)});q('#chips').innerHTML=list.map(c=>'<span class="chip">'+esc(lang==='ar'?(CAT_AR[c]||c):c)+'</span>').join('')}
function link(id,url,label){const a=q(id);a.hidden=!url;if(url)a.href=url;a.querySelector('span').textContent=label}
function renderContacts(){const t=D[lang];link('#loc',String(cfg.locationUrl||''),t.loc);link('#wa',wa(cfg.whatsapp||''),t.wa);link('#ig',social(cfg.instagram||'','https://instagram.com/'),t.ig);link('#tk',social(cfg.tiktok||'','https://www.tiktok.com/@'),t.tk)}
function render(){buildFeatured();renderBrand();renderText();renderCats();renderContacts();drawWheel();showDetail(false);gallery()}
function initInteractions(){bindWheel();q('#langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('cng_website_lang',lang);render()};let sx=0;const gv=q('#galleryViewport');gv.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});gv.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx,n=qa('.gallery-card').length;if(Math.abs(dx)>40&&n){galleryIndex=(galleryIndex+(dx<0?1:-1)+n)%n;moveGallery()}},{passive:true});new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('reveal')}),{threshold:.18}).observe(q('#gallery'));addEventListener('resize',()=>{drawWheel();moveGallery()},{passive:true})}
Promise.all([db.ref('/settings').once('value'),db.ref('/products').once('value'),db.ref('/website/config').once('value')]).then(([s,p,c])=>{settings=s.val()||{};const d=p.val();products=d?Object.values(d).filter(Boolean):[];cfg=c.val()||{};sigS=sig(settings);sigP=sig(products);sigC=sig(cfg);render();initInteractions();db.ref('/settings').on('value',x=>{const v=x.val()||{},z=sig(v);if(z===sigS)return;sigS=z;settings=v;render()});db.ref('/products').on('value',x=>{const d=x.val(),v=d?Object.values(d).filter(Boolean):[],z=sig(v);if(z===sigP)return;sigP=z;products=v;render()});db.ref('/website/config').on('value',x=>{const v=x.val()||{},z=sig(v);if(z===sigC)return;sigC=z;cfg=v;render()})}).catch(()=>{render();initInteractions()});
})();